version: '2'
services:
  nginx_shiny_node:
    build: 
      context: .
    ports:
      - "8880:80"
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local4"
