version: '2'
services:
  shinyserver:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8838:3838"
    volumes:
      - /mirror/data/pub/users/paciorek/ShinyApps:/mirror/data/pub/users/paciorek/ShinyApps
      - /mirror/data/pub/users/curt/ShinyApps:/mirror/data/pub/users/curt/ShinyApps
      - /mirror/data/pub/users/scf1/ShinyApps:/mirror/data/pub/users/scf1/ShinyApps
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local4"
