version: '2'

services:
  shiny1-dev:
    extends:
      file: common.yml
      service: shiny
    ports:
      - "8848:3838"
    container_name: shiny1-dev

  shiny2-dev:
    extends:
      file: common.yml
      service: shiny
    ports:
      - "8849:3838"
    container_name: shiny2-dev

  shiny3-dev:
    extends:
      file: common.yml
      service: shiny
    ports:
      - "8850:3838"
    container_name: shiny3-dev

  shiny4-dev:
    extends:
      file: common.yml
      service: shiny
    ports:
      - "8851:3838"
    container_name: shiny4-dev
