version: '2'

services:
  shiny:
    image: ucbscf/docker-shiny:03fb20a
    ports:
      - "8848-8853:3838"
    volumes:
      - /mirror/data/pub/shiny:/srv/shiny-apps
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"
#        tag: "{{.ImageName}}"
