version: '3'

services:
  shiny:
    container_name: shiny
    image: ucbscf/docker-shiny:7bf5a9c
    ports:
      - "8848-8853:3838"
    volumes:
      - /mirror/data/pub/shiny:/srv/shiny-apps
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"
        tag: "{{.Name}}"

  #shiny-dev:
  #  image: ucbscf/docker-shiny:7bf5a9c
  #  ports:
  #    - "8838:3838"
  #  volumes:
  #    - /mirror/data/pub/shiny:/srv/shiny-apps
  #  logging:
  #    driver: syslog
  #    options:
  #      syslog-facility: "local7"
  #      tag: "{{.ImageName}}"
