version: '2'

services:
  shiny1:
    extends:
      file: common.yml
      service: shiny
    container_name: shiny1
    ports:
      - "8848:3838"

  shiny2:
    extends:
      file: common.yml
      service: shiny
    container_name: shiny2
    ports:
      - "8849:3838"

  shiny3:
    extends:
      file: common.yml
      service: shiny
    container_name: shiny3
    ports:
      - "8850:3838"

  shiny4:
    extends:
      file: common.yml
      service: shiny
    container_name: shiny4
    ports:
      - "8851:3838"
