version: '2'

services:
  shiny1-prod:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8838:3838"
    container_name: shiny2-prod
    volumes:
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"

  shiny2-prod:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8839:3838"
    container_name: shiny3-prod
    volumes:
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"

  shiny3-prod:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8840:3838"
    container_name: shiny4-prod
    volumes:
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"

  shiny4-prod:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8841:3838"
    container_name: shiny1-prod
    volumes:
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"
