version: '2'

services:
  shiny:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    volumes:
      - /mirror/data/pub/shiny:/srv/shiny-apps
    #restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"
#        tag: "{{.ImageName}}"
