version: '2'

services:
  shinyserver_1:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8838:3838"
    container_name: scf_shinyserver
    volumes:
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"

  shinyserver_2:
    build: 
      context: .
      args:
        - SITE_SHINY_USER_ID
    ports:
      - "8838:3838"
    container_name: scf_shinyserver
    volumes:
      - /mirror/data/pub/users/alucas/ShinyApps:/mirror/data/pub/users/alucas/ShinyApps
      - /usr/local/common/etc/skel:/home/skel
    restart: always
    logging:
      driver: syslog
      options:
        syslog-facility: "local7"
